name: resbite_app
description: "Resbite - Activities for families"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  
  # Firebase (removed - now using Supabase for authentication and storage)
  # No longer needed after Supabase migration
  
  # Supabase
  supabase_flutter: ^2.3.1
  share_plus: ^11.0.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.2.2
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  geolocator: ^14.0.0
  connectivity_plus: ^6.1.3
  permission_handler: ^12.0.0+1
  timeago: ^3.6.1
  path: ^1.9.1
  lottie: ^3.3.0
  shadcn_ui: ^0.27.3
  tailwind_cli: ^0.7.7
  flutter_contacts: ^1.1.9+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.8
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo.svg
    - assets/illustrations/
    - assets/animations/
    - "assets/Resbites Illustrations/SVGs/"
    - .env
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700